=== tikoM/xmlExample/xmls/staff1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="xsdTest"
           xmlns="xsdTest"
           elementFormDefault="qualified">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="staff" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="firstname"/>
                            <xs:element type="xs:string" name="lastname"/>
                            <xs:element type="xs:string" name="nickname"/>
                            <xs:element type="xs:int" name="salary"/>
                        </xs:sequence>
                        <xs:attribute type="xs:short" name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tikoM/xmlExample/xmls/staff.xml
<?xml version="1.0"?>
<!--<!DOCTYPE company
        [
                <!ELEMENT company (staff, staff)>
                <!ELEMENT staff (firstname,lastname,nickname,salary)>
                <!ATTLIST staff id CDATA "0">
                <!ELEMENT firstname (#PCDATA)>
                <!ELEMENT lastname (#PCDATA)>
                <!ELEMENT nickname (#PCDATA)>
                <!ELEMENT salary (#PCDATA)>
                ]>-->
<company
        xmlns="xsdTest"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="xsdTest staff1.xsd">
    <staff id="1001">
        <firstname>22</firstname>
        <lastname>mook kim</lastname>
        <nickname>mkyong</nickname>
        <salary>100000</salary>
    </staff>
    <staff id="2001">
        <firstname>low</firstname>
        <lastname>yin fong</lastname>
        <nickname>fong fong</nickname>
        <salary>200000</salary>
    </staff>
</company>
